## 1. Importing libraries

referred to the official document. 
[OpenCV](https://docs.opencv.org/4.x/d5/de5/tutorial_py_setup_in_windows.html)


In [5]:

import cv2 as cv
import numpy as np
import glob2 as glob
import matplotlib.pyplot as plt

In [6]:
print( cv.__version__ )

4.11.0


## 2. Understanding the usage of OpenCV with code from official document

### 2-0. practicing using functions from np and cv

In [28]:
np.zeros((2*7,3), np.float32)
# objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# reason why using 2*7 instead of 14 -> it represents a size of the grid pattern 

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [6, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [5, 2],
       [6, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [5, 3],
       [6, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [5, 4],
       [6, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [5, 5],
       [6, 5]])

In [29]:
np.mgrid[0:7,0:6].T.reshape(-1,2)

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [6, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [5, 2],
       [6, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [5, 3],
       [6, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [5, 4],
       [6, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [5, 5],
       [6, 5]])

#### 📍 More about the method 'cornerSubPix'
https://docs.opencv.org/4.x/dd/d1a/group__imgproc__feature.html#ga354e0d7c86d0d9da75de9b9701a9a87e

```python
@_typing.overload
def cornerSubPix(image: cv2.typing.MatLike, corners: cv2.typing.MatLike, winSize: cv2.typing.Size, zeroZone: cv2.typing.Size, criteria: cv2.typing.TermCriteria) -> cv2.typing.MatLike: ...
@_typing.overload
def cornerSubPix(image: UMat, corners: UMat, winSize: cv2.typing.Size, zeroZone: cv2.typing.Size, criteria: cv2.typing.TermCriteria) -> UMat: ...
```

image: tuple. - should be grayscaled.
corners: tuple. - return value of findChessboardCorners
```python
@_typing.overload
def findChessboardCorners(image: cv2.typing.MatLike, patternSize: cv2.typing.Size, corners: cv2.typing.MatLike | None = ..., flags: int = ...) -> tuple[bool, cv2.typing.MatLike]: ...
@_typing.overload
def findChessboardCorners(image: UMat, patternSize: cv2.typing.Size, corners: UMat | None = ..., flags: int = ...) -> tuple[bool, UMat]: ...

```

winSize

zeroZone


https://www.tutorialspoint.com/how-to-find-patterns-in-a-chessboard-using-opencv-python

### 2-1.1. Additional code blocks for testing since the errors have occurred while executing 2-1

In [15]:
import cv2 as cv
from datetime import date

chessboardsize = (8,6)

# read input image
filepath = "images/sample.jpg"
srcimg = cv.imread(filepath)
cv.imshow(filepath, srcimg)
cv.waitKey(0) 

# convert the input image to a grayscale
grayscaled = cv.cvtColor(srcimg, cv.COLOR_BGR2GRAY)

# Find the chess board corners
ret, corners = cv.findChessboardCorners(grayscaled, chessboardsize, None)
print(ret)

# terminating criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
if ret == True:
   corners2 = cv.cornerSubPix(grayscaled,corners,(11,11),(-1,-1),criteria)

# Draw and display the corners
   outputimg = cv.drawChessboardCorners(srcimg, chessboardsize, corners, ret)
   cv.imshow('Chessboard',outputimg)
   cv.waitKey(0)

   today = date.today()
   outputpath = "output/" + date.isoformat(today) + ".jpg"
   print("file name: " + outputpath)
   status = cv.imwrite(outputpath, outputimg)
   print(status)


True
file name: output/2025-01-31.jpg
True


### 2-1. Understanding of the codes; simplified version

In [50]:
import cv2 as cv

with_sample = False 


if with_sample :
    chessboardsize = (8, 6)
    filepath = "images/sample.jpg"
else :
    chessboardsize = (30, 20)
    filepath = "images/camera_calib5.jpg"

# fetching source image file 
srcimg = cv.imread(filepath)
cv.imshow(filepath, srcimg)
cv.waitKey(0) # how long to wait for showing the next image. unit: ms. 5000: wait for 5 seconds and then show the next img. 
# if we doesn't use this key, kernel crashes. 

# making the image grayscaled. 
# https://www.geeksforgeeks.org/python-opencv-cv2-cvtcolor-method/
grayscaledimg = cv.cvtColor(srcimg, cv.COLOR_BGR2GRAY)
cv.imshow(filepath +' grayscaled', grayscaledimg)
cv.waitKey(0) 

ret, corners = cv.findChessboardCorners(grayscaledimg, chessboardsize, None)
# print(ret, corners)
print(ret)

# print("Before Criteria") 
# termination criteria for corner refinement.
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001) 
# TODO: find out how the value of cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER results out as 3
    # tried to check the files and searched using grep (grep -r "TERM_CRITERIA_EPS" .) but I couldn't find where the value is assigned. 
    
# TERM_CRITERIA_EPS : criteria epsilon. - cease the iteration when the corner posiiton moves by less thean it. 
# print(criteria) 

if ret == True:
    # print("if statement - IN")
    ## refining the corner coordinates. 
    corners2 = cv.cornerSubPix(grayscaledimg,corners, (11,11), (-1,-1), criteria)
    # print(corners2)
    # (-1,-1): not to reject anything

    img = cv.drawChessboardCorners(grayscaledimg, chessboardsize, corners2, ret)
    window_name = 'img'
    cv.imshow(window_name, img)
    cv.waitKey(0)
    # cv.waitKey(500)

    today = date.today()
    outputpath = "output/" + date.isoformat(today) + ".jpg"
    print("file name: " + outputpath)
    status = cv.imwrite(outputpath, outputimg)
    print(status)
    
 
#cv.destroyAllWindows()

False


### 2.1.2 Using Glob and loop statement to handle multiple images with the base code above. 

In [6]:

import cv2 as cv
import numpy as np
import glob2 as glob

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# print(objp)
 
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
 
images_regex = 'images/camera_calib*.jpg'
images = glob.glob(images_regex) # recursively retrieving files with regex
 
for idx, fname  in enumerate(images):
    if idx == 0 or idx == len(images) - 1: print(idx)
    img = cv.imread(fname)
    grayscaledimg = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    cv.imshow(fname, grayscaledimg)
    cv.waitKey(0)
 
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(grayscaledimg, (31,23), None)
    # if idx == 0 or idx == len(images) - 1: 
    print(idx, ret) # 10, 19, 22, 24, 5
    # Question: some of the sample files returned True for the function fincChessboardCorners and some are not. 
    # -> https://stackoverflow.com/questions/66225558/cv2-findchessboardcorners-fails-to-find-corners
 
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
 
        corners2 = cv.cornerSubPix(grayscaledimg,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
 
        # Draw and display the corners
        cv.drawChessboardCorners(img, (31,23), corners2, ret)
        window_name = fname + ' outputimg'
        cv.imshow(window_name, img)
        # cv.waitKey(500)
        cv.waitKey(0)
 
#cv.destroyAllWindows()

0
0 False
1 True
2 False
3 False
4 False
5 False
6 False
7 False
8 False
9 False
10 True
11 False
12 False
13 False
14 True
15 False
16 True
17 False
18 False
19 False
20 True
21 False
22 False
23 False
24
24 False


## 3. Calibration 

In [15]:
import cv2 as cv
import numpy as np

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((23*31, 3), np.float32)
objp[:,:2] = np.mgrid[0:31,0:23].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

# imgpath = 'images/sample.jpg'
imgpath = 'images/camera_calib5.jpg'
img = cv.imread(imgpath)

grayscaledimg = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow(imgpath, grayscaledimg)
cv.waitKey(0)
ret, corners = cv.findChessboardCorners(grayscaledimg, (31,23), None)
print(ret)

if ret == True:
    objpoints.append(objp)

    corners2 = cv.cornerSubPix(grayscaledimg,corners, (11, 11), (-1, -1), criteria)
    imgpoints.append(corners2)

    # Draw and display the corners
    cv.drawChessboardCorners(img, (31, 23), corners2, ret)
    window_name = fname + ' outputimg'
    cv.imshow(window_name, img)
    cv.waitKey(0)

    ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, grayscaledimg.shape[::-1], None, None)
    # TROUBLE SHOOTING
    # Number of object and image points must be equal (expected: 'numberOfObjectPoints == numberOfImagePoints')
    # -> the value of objpoints and imgpoints' is not identical. 
    print(ret, mtx, dist, rvecs, tvecs)

True
0.2789343940438358 [[459.49627036   0.         462.98078721]
 [  0.         425.9391768  332.55095914]
 [  0.           0.           1.        ]] [[-0.13575777  0.0247265   0.00342986  0.00018729 -0.00074961]] (array([[-0.0740356 ],
       [ 0.00389051],
       [ 0.07810778]]),) (array([[-12.03832935],
       [-13.96143027],
       [ 20.05135273]]),)


mtx: camera matrix
dist: distortion coefficient
rvecs: rotation
tvecs: translation vectors

## 4. Correcting distortion

In [5]:
import sys
print(sys.executable)

/Users/kimjimin/Developer/camera-calibration-trial/.venv/bin/python


In [9]:
import cv2 as cv

In [7]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

W = 23
L = 31

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((W*L, 3), np.float32)
objp[:,:2] = np.mgrid[0:L,0:W].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

# imgpath = 'images/sample.jpg'
imgname = 'camera_calib5.jpg'
imgpath = f'images/{imgname}'
img = cv.imread(imgpath)
cv.imshow(imgname, img)
cv.waitKey(0)
cv.destroyAllWindows()

grayscaledimg = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
grayscaledimgtitle = imgname + " grayscaled"
cv.imshow(grayscaledimgtitle, grayscaledimg)
cv.waitKey(0)
cv.destroyAllWindows()
# print(grayscaledimg.min(), grayscaledimg.max())
# plt.imshow(grayscaledimg)
# plt.axis("off")
# plt.show()

ret, corners = cv.findChessboardCorners(grayscaledimg, (L,W), None)
print("Are Chessboard corners detected:\n", ret, "\n")

if ret == True:
    objpoints.append(objp)

    corners2 = cv.cornerSubPix(grayscaledimg, corners, (11, 11), (-1, -1), criteria)
    imgpoints.append(corners2)

    # Draw and display the corners
    cv.drawChessboardCorners(img, (L, W), corners2, ret)
    window_name = imgpath + ' with corner'
    cv.imshow(window_name,img)
    cv.waitKey(0)
    cv.destroyAllWindows()
    # plt.imshow(imgwithcorner)
    # plt.axis("off")
    # plt.show()

    ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, grayscaledimg.shape[::-1], None, None)
    print(ret)
    print("Camera Matrix:\n", mtx, "\n")
    print("Distortion Coefficient:\n", dist, "\n")
    print(rvecs, "\n", tvecs)

    h,  w = grayscaledimg.shape[:2]
    newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

    # undistort
    dst = cv.undistort(grayscaledimg, mtx, dist, None, newcameramtx)
    
    # crop the image
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]
    outputpath = f"output/{imgname}"
    cv.imwrite(outputpath, dst)
    # outputimg = plt.imread(outputpath)
    # plt.imshow(outputimg) 
    # plt.axis("off")
    # plt.show()
    outputimg = cv.imread(outputpath)
    cv.imshow(window_name, outputimg)
    cv.waitKey(0)
    cv.destroyAllWindows()
    cv.waitKey(1000)

Are Chessboard corners detected:
 True 

0.2789344851009926
Camera Matrix:
 [[459.49635782   0.         462.98078123]
 [  0.         425.93925902 332.55096499]
 [  0.           0.           1.        ]] 

Distortion Coefficient:
 [[-0.13575781  0.02472651  0.00342986  0.00018729 -0.00074961]] 

(array([[-0.07403562],
       [ 0.00389051],
       [ 0.07810778]]),) 
 (array([[-12.0383291 ],
       [-13.96143052],
       [ 20.05135661]]),)


# Final 

In [8]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

W = 23
L = 31

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((W*L, 3), np.float32)
objp[:,:2] = np.mgrid[0:L,0:W].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

imgname = 'camera_calib5.jpg'
imgpath = f'images/{imgname}'
img = cv.imread(imgpath)
cv.imshow(imgname, img)
cv.waitKey(0)
cv.destroyAllWindows()

grayscaledimg = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
grayscaledimgtitle = imgname + " grayscaled"
cv.imshow(grayscaledimgtitle, grayscaledimg)
cv.waitKey(0)
cv.destroyAllWindows()

ret, corners = cv.findChessboardCorners(grayscaledimg, (L,W), None)
print("Are Chessboard corners detected:\n", ret, "\n")

if ret == True:
    objpoints.append(objp)

    corners2 = cv.cornerSubPix(grayscaledimg, corners, (11, 11), (-1, -1), criteria)
    imgpoints.append(corners2)

    # Draw and display the corners
    cv.drawChessboardCorners(img, (L, W), corners2, ret)
    window_name = imgpath + ' with corner'
    cv.imshow(window_name,img)
    cv.waitKey(0)
    cv.destroyAllWindows()

    ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, grayscaledimg.shape[::-1], None, None)
    print(ret)
    print("Camera Matrix:\n", mtx, "\n")
    print("Distortion Coefficient:\n", dist, "\n")
    print(rvecs, "\n", tvecs)

    h,  w = grayscaledimg.shape[:2]
    newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

    dst = cv.undistort(grayscaledimg, mtx, dist, None, newcameramtx)
    
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]
    outputpath = f"output/{imgname}"
    cv.imshow(window_name, dst)
    cv.waitKey(0)

    cv.destroyAllWindows()
    cv.waitKey(1000)

Are Chessboard corners detected:
 True 

0.2789344851009926
Camera Matrix:
 [[459.49635782   0.         462.98078123]
 [  0.         425.93925902 332.55096499]
 [  0.           0.           1.        ]] 

Distortion Coefficient:
 [[-0.13575781  0.02472651  0.00342986  0.00018729 -0.00074961]] 

(array([[-0.07403562],
       [ 0.00389051],
       [ 0.07810778]]),) 
 (array([[-12.0383291 ],
       [-13.96143052],
       [ 20.05135661]]),)
